#!/usr/bin/env bash

# HotelBook Deployment - Automated Setup Instructions
# This file contains the complete deployment setup

echo "🚀 HotelBook GitHub Actions + Railway Deployment Setup"
echo "======================================================="
echo ""

# Step 1: GitHub Prerequisites
echo "✅ STEP 1: GitHub Prerequisites"
echo "   Status: You've already:"
echo "   ✓ Created GitHub repository"
echo "   ✓ Pushed code to main branch"
echo ""

# Step 2: Files Created
echo "✅ STEP 2: Deployment Files Created"
echo "   The following files have been created:"
echo ""
echo "   📂 Configuration Files:"
echo "      • .github/workflows/deploy.yml      - CI/CD workflow"
echo "      • railway.json                      - Railway configuration"
echo ""
echo "   📖 Documentation Files:"
echo "      • DEPLOY_QUICK_START.md             - Quick 5-minute guide"
echo "      • DEPLOYMENT.md                     - Detailed deployment guide"
echo "      • GITHUB_ACTIONS.md                 - CI/CD documentation"
echo "      • DEPLOYMENT_FILES_SUMMARY.md       - Files overview"
echo ""
echo "   🛠️ Utility Files:"
echo "      • scripts/test-build.sh             - Local build test script"
echo ""
echo "   📝 Updated Files:"
echo "      • package.json                      - Added build scripts"
echo "      • server/package.json               - Added postinstall hook"
echo "      • server/.env.example               - Updated variables"
echo ""

# Step 3: Next Steps
echo "✅ STEP 3: Setup Checklist"
echo ""
echo "   🔷 IMMEDIATE (Next 10 minutes):"
echo ""
echo "      1. Create Railway Account"
echo "         → Visit https://railway.app"
echo "         → Sign up (GitHub login recommended)"
echo ""
echo "      2. Generate Railway Token"
echo "         → Railway Dashboard"
echo "         → Settings → Tokens"
echo "         → Click 'Create Token'"
echo "         → Copy token (⚠️ Keep secret!)"
echo ""
echo "      3. Add GitHub Secret"
echo "         → GitHub Repo → Settings"
echo "         → Secrets and variables → Actions"
echo "         → New repository secret"
echo "         → Name: RAILWAY_TOKEN"
echo "         → Value: <paste token>"
echo ""
echo "      4. Test Build Locally (Optional but Recommended)"
echo "         → chmod +x scripts/test-build.sh"
echo "         → ./scripts/test-build.sh"
echo ""
echo "   🔷 CONFIGURATION (Next 20 minutes):"
echo ""
echo "      5. Create Railway PostgreSQL Service"
echo "         Option A - Using Railway CLI:"
echo "           → npm install -g @railway/cli"
echo "           → railway login"
echo "           → cd /path/to/hotelbook"
echo "           → railway init"
echo "           → railway add --service postgres"
echo ""
echo "         Option B - Using Dashboard:"
echo "           → railway.app → New Project"
echo "           → Add PostgreSQL"
echo "           → Add Node.js"
echo "           → Link GitHub repo"
echo ""
echo "      6. Set Environment Variables in Railway"
echo "         Railway Dashboard → Project → Variables"
echo ""
echo "         Critical Variables:"
echo "           NODE_ENV=production"
echo "           DATABASE_URL=<from postgres service>"
echo "           JWT_SECRET=<generate: node -e 'console.log(require(\"crypto\").randomBytes(32).toString(\"hex\"))'>"
echo "           CLIENT_URL=<your frontend URL>"
echo ""
echo "         OAuth Variables:"
echo "           GOOGLE_CLIENT_ID=<from Google Console>"
echo "           GOOGLE_CLIENT_SECRET=<from Google Console>"
echo "           GITHUB_CLIENT_ID=<from GitHub Settings>"
echo "           GITHUB_CLIENT_SECRET=<from GitHub Settings>"
echo ""
echo "         M-Pesa Variables:"
echo "           MPESA_CONSUMER_KEY=<from Safaricom>"
echo "           MPESA_CONSUMER_SECRET=<from Safaricom>"
echo "           MPESA_INITIATOR_PASSWORD=<from Safaricom>"
echo "           MPESA_CALLBACK_URL=https://your-railway-url.up.railway.app/api/payments/callback"
echo ""
echo "   🔷 DEPLOYMENT (Final Step):"
echo ""
echo "      7. Push to Main"
echo "         → git add ."
echo "         → git commit -m 'Add GitHub Actions deployment'"
echo "         → git push origin main"
echo ""
echo "      8. Monitor Deployment"
echo "         → GitHub: Repo → Actions tab"
echo "         → Look for workflow run"
echo "         → Follow logs in real-time"
echo "         → Should complete in 6-10 minutes"
echo ""
echo "      9. Test Application"
echo "         → Visit https://hotelbook-api.up.railway.app/api/hotels"
echo "         → Should see JSON list of hotels"
echo ""

# Step 4: Documentation
echo "🎓 DOCUMENTATION QUICK LINKS"
echo ""
echo "   Need a quick reference?"
echo "      → Read: DEPLOY_QUICK_START.md"
echo ""
echo "   Need detailed steps?"
echo "      → Read: DEPLOYMENT.md"
echo ""
echo "   Want to understand the workflow?"
echo "      → Read: GITHUB_ACTIONS.md"
echo ""
echo "   Deployment failed?"
echo "      → Check GitHub Actions logs"
echo "      → Read: DEPLOYMENT.md (Troubleshooting section)"
echo ""

# Step 5: Important Notes
echo "⚠️  IMPORTANT NOTES"
echo ""
echo "   • Never commit .env files"
echo "   • Always use GitHub Secrets for sensitive data"
echo "   • Railway environment variables ≠ GitHub Secrets"
echo "   • First build takes 6-10 minutes (subsequent builds faster)"
echo "   • M-Pesa callbacks require public URL (localhost won't work)"
echo "   • Test locally with ./scripts/test-build.sh before pushing"
echo ""

# Step 6: Success Indicators
echo "✨ SUCCESS INDICATORS"
echo ""
echo "   You'll know it's working when:"
echo ""
echo "   ✓ GitHub Actions workflow shows green checkmark"
echo "   ✓ Railway dashboard shows 'Successfully deployed'"
echo "   ✓ API endpoint returns hotel data"
echo "   ✓ No errors in Railway logs"
echo ""
echo "   Run this to check:"
echo "      curl https://hotelbook-api.up.railway.app/api/hotels"
echo ""

# Step 7: Support
echo "🆘 NEED HELP?"
echo ""
echo "   1. Check GitHub Actions logs for build errors"
echo "   2. Run ./scripts/test-build.sh locally to debug"
echo "   3. Verify all environment variables are set in Railway"
echo "   4. Review troubleshooting sections in documentation"
echo ""
echo "   Files to check:"
echo "      • .github/workflows/deploy.yml"
echo "      • railway.json"
echo "      • server/.env.example"
echo ""

echo ""
echo "======================================================="
echo "Ready to deploy? Follow the checklist above! 🚀"
echo "======================================================="
echo ""
